#!/bin/sh

echo "Running ./gradlew spotlessApply..."
./gradlew spotlessApply

SPOTLESS_RESULT=$?

if [ $SPOTLESS_RESULT -ne 0 ]; then
    echo "--------------------------------------------------"
    echo "Spotless failed to apply formatting! Commit aborted."
    echo "--------------------------------------------------"
    exit 1
fi

echo "Running ./gradlew build prior to commit..."
./gradlew build

BUILD_RESULT=$?

if [ $BUILD_RESULT -ne 0 ]; then
    echo "--------------------------------------------------"
    echo "Gradle build failed! Commit aborted."
    echo "Fix the build errors above before committing."
    echo "--------------------------------------------------"
    exit 1
fi

exit 0